# Development only
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  rails:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    command: /usr/bin/supervisord
    volumes:
      - .:/app
    depends_on:
      - postgres
    env_file:
      - './docker-bin/env.sh'

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ./docker-bin/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - rails

volumes:
  postgres: